<?php
error_reporting(0); if (!isset($_SESSION["mikhmon"])) { header("Location:../admin.php?id=login"); exit; }
$active=$API->comm('/ppp/active/print');
if (function_exists('mikhmonIsMitra') && mikhmonIsMitra()) {
  $mitraPppUsernames = mikhmonMitraUsernamesByService($session, 'pppoe');
  $active = array_values(array_filter((array) $active, function ($row) use ($mitraPppUsernames) {
    return isset($row['name']) && isset($mitraPppUsernames[(string) $row['name']]);
  }));
}
?><div class="row"><div class="col-12"><div class="card"><div class="card-header"><h3><i class="fa fa-wifi"></i> <?= $_ppp_active ?></h3></div><div class="card-body"><div class="overflow box-bordered"><table id="dataTable" class="table table-bordered table-hover text-nowrap"><thead><tr><th class="text-center"><?= count($active) ?></th><th><?= $_user_name ?></th><th>Service</th><th>Address</th><th>Uptime</th><th>Caller ID</th><th><?= $_action ?></th></tr></thead><tbody><?php foreach($active as $row): ?><tr><td class="text-center"><?php if (!(function_exists('mikhmonIsMitra') && mikhmonIsMitra())): ?><a href="./?remove-pactive=<?= rawurlencode($row['.id']) ?>&session=<?= $session ?>" onclick="return confirm('Disconnect this user?')"><i class="fa fa-minus-square text-danger"></i></a><?php else: ?><i class="fa fa-wifi text-green"></i><?php endif; ?></td><td><?= htmlspecialchars(isset($row['name'])?$row['name']:'') ?></td><td><?= htmlspecialchars(isset($row['service'])?$row['service']:'') ?></td><td><?= htmlspecialchars(isset($row['address'])?$row['address']:'') ?></td><td><?= htmlspecialchars(isset($row['uptime'])?$row['uptime']:'') ?></td><td><?= htmlspecialchars(isset($row['caller-id'])?$row['caller-id']:'') ?></td><td><?php if (!(function_exists('mikhmonIsMitra') && mikhmonIsMitra())): ?><a href="./?secret=<?= rawurlencode(isset($row['name'])?$row['name']:'') ?>&session=<?= $session ?>"><i class="fa fa-edit"></i></a><?php else: ?>-<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div></div>
